'\"t
.TH "SESSION-MONITOR" "8" "20\ \&MAY\ \&2022" "SESSION-MONITOR 1.0" "SESSION MONITORING SERVICE"

.SH "NAME"
session-monitoring
.SH "DESCRIPTION"
\fBsession-monitoring\fR - monitors users connected to system via ssh every 30 seconds. When an external user connects via ssh, a notification (notify mechanism) should be displayed to user with name of the user who has connected to the system remotely.
.SH "AUTHOR"
Dmitriy Rodionov